name: NeverHungryPlugin
version: 1.0
main: me.tauntaunchewie.neverhungry.NeverHungryPlugin
api-version: 1.18

commands:
  neverhungry:
    description: Enables/disables hunger for all players
    usage: /<command> on/off/status
    permission: neverhungryplugin.set
    permission-message: You do not have permission to execute that command.

permissions:
  neverhungryplugin.seeplugin:
    description: Basic ability to see the plugin
    default: op
  neverhungryplugin.set:
    description: Permission to enable and disable pooping
    default: op